// Prototype sample data for the Activity log (from the original HTML), newest first.
// Every change on the site: who made it, what it was before and after, and from where.
// Swap for an API call in sections.functions.ts later; the page only uses ActivityRow.
import type { ActivityLink, ActivityRow } from "./section-types";

type Entry = Omit<ActivityRow, "id" | "item" | "before" | "after"> & {
  item?: string;
  before?: string;
  after?: string;
};

const EDGE = "Edge · Windows · Dubai";
const IPHONE = "Safari · iPhone · Cairo";
const MAC = "Chrome · Mac · Cairo";
const NASR = "Chrome · Windows · Nasr City";

const order = (id: string): ActivityLink => ({ kind: "order", id });
const ret = (id: string): ActivityLink => ({ kind: "return", id });
const product = (id: string): ActivityLink => ({ kind: "product", id });
const enquiry = (id: string): ActivityLink => ({ kind: "enquiry", id });
const section = (s: string): ActivityLink => ({ kind: "section", section: s });

const ENTRIES: Entry[] = [
  {
    day: "Today",
    time: "21:42",
    who: "System",
    area: "Orders",
    action: "New order placed",
    item: "ZL-10494",
    link: order("ZL-10494"),
    after: "6,450 EGP · Paymob card",
    from: "Website",
  },
  {
    day: "Today",
    time: "21:05",
    who: "Ramy Bakr",
    area: "Sign-in",
    action: "Signed out",
    from: EDGE,
  },
  {
    day: "Today",
    time: "20:15",
    who: "System",
    area: "Enquiries",
    action: "New corporate enquiry",
    item: "ENQ-318 · Meridian Real Estate",
    link: enquiry("ENQ-318"),
    after: "120 pieces",
    from: "Website form",
  },
  {
    day: "Today",
    time: "19:48",
    who: "Ahmed",
    area: "Orders",
    action: "Changed order status",
    item: "ZL-10489",
    link: order("ZL-10489"),
    before: "Processing",
    after: "Ready to ship",
    from: NASR,
  },
  {
    day: "Today",
    time: "19:40",
    who: "Ahmed",
    area: "Delivery",
    action: "Booked courier",
    item: "ZL-10489",
    link: order("ZL-10489"),
    before: "Not booked",
    after: "Bosta · BST-88214185",
    from: NASR,
  },
  {
    day: "Today",
    time: "18:02",
    who: "Ahmed",
    area: "Returns",
    action: "Changed return status",
    item: "RMA-2035",
    link: ret("RMA-2035"),
    before: "Received",
    after: "Inspecting",
    from: NASR,
  },
  {
    day: "Today",
    time: "17:30",
    who: "Zain",
    area: "Prices",
    action: "Changed offer price",
    item: "Good Girl Eau de Parfum 80ml",
    link: product("P1003"),
    before: "6,950 EGP",
    after: "6,450 EGP",
    from: IPHONE,
  },
  {
    day: "Today",
    time: "16:40",
    who: "Zain",
    area: "Products",
    action: "Edited Arabic description",
    item: "Swarovski Millenia Necklace",
    link: product("P1011"),
    before: "قلادة ميلينيا بكريستالات…",
    after: "قلادة ميلينيا من سواروفسكي بكريستالات مقطوعة…",
    from: IPHONE,
  },
  {
    day: "Today",
    time: "16:12",
    who: "Ramy Bakr",
    area: "Discounts",
    action: "Created discount code",
    item: "WELCOME10",
    link: section("discounts"),
    after: "10% off first order · ends 31 Oct",
    from: EDGE,
  },
  {
    day: "Today",
    time: "15:12",
    who: "System",
    area: "Stock",
    action: "Went to low stock",
    item: "Clarins Extra-Firming Night Cream 50ml",
    link: product("P1010"),
    before: "3 left",
    after: "2 left",
    from: "Automatic",
  },
  {
    day: "Today",
    time: "14:55",
    who: "Ahmed",
    area: "Stock",
    action: "Adjusted stock · delivery received",
    item: "Versace Eros Eau de Toilette 100ml",
    link: product("P1004"),
    before: "12",
    after: "17",
    from: NASR,
  },
  {
    day: "Today",
    time: "14:30",
    who: "Ramy Bakr",
    area: "Content",
    action: 'Changed homepage "Curated for You"',
    item: "Homepage",
    link: section("content"),
    before: "8 products",
    after: "10 products",
    from: EDGE,
  },
  {
    day: "Today",
    time: "13:10",
    who: "Zain",
    area: "Enquiries",
    action: "Moved enquiry stage",
    item: "ENQ-316 · Horizon Bank",
    link: enquiry("ENQ-316"),
    before: "Contacted",
    after: "Quoted",
    from: IPHONE,
  },
  {
    day: "Today",
    time: "12:40",
    who: "Ramy Bakr",
    area: "Reports",
    action: "Downloaded report (Excel)",
    item: "Reports · last 30 days",
    link: section("reports"),
    from: EDGE,
  },
  {
    day: "Today",
    time: "12:02",
    who: "Zain",
    area: "Sign-in",
    action: "Signed in",
    after: "2-step code verified",
    from: IPHONE,
  },
  {
    day: "Today",
    time: "11:05",
    who: "Ramy Bakr",
    area: "Refunds",
    action: "Approved refund",
    item: "RMA-2036",
    link: ret("RMA-2036"),
    before: "Awaiting approval",
    after: "8,400 EGP to Paymob wallet",
    from: EDGE,
  },
  {
    day: "Today",
    time: "10:20",
    who: "Ramy Bakr",
    area: "Prices",
    action: "Changed price",
    item: "Guess Iconic Gold-Tone Watch",
    link: product("P1013"),
    before: "10,900 EGP",
    after: "11,500 EGP",
    from: EDGE,
  },
  {
    day: "Today",
    time: "09:14",
    who: "Ahmed",
    area: "Sign-in",
    action: "Signed in",
    after: "2-step code verified",
    from: NASR,
  },
  {
    day: "Today",
    time: "09:02",
    who: "Ramy Bakr",
    area: "Sign-in",
    action: "Signed in",
    after: "2-step code verified",
    from: EDGE,
  },
  {
    day: "Today",
    time: "08:47",
    who: "System",
    area: "Sign-in",
    action: "Failed sign-in · wrong password",
    item: "ahmed",
    link: section("staff"),
    after: "Attempt 1 of 5 · account still open",
    from: "Chrome · Android · Giza",
    flag: true,
  },
  {
    day: "Yesterday",
    time: "22:10",
    who: "Ramy Bakr",
    area: "Team",
    action: "Changed role",
    item: "Nada Samir",
    link: section("staff"),
    before: "View only",
    after: "Content editor",
    from: EDGE,
  },
  {
    day: "Yesterday",
    time: "18:30",
    who: "Zain",
    area: "Selling control",
    action: "Switched to Enquiry",
    item: "Hugo Boss · Leather Goods",
    link: section("selling"),
    before: "Add to Cart",
    after: "Enquiry",
    from: MAC,
  },
  {
    day: "Yesterday",
    time: "17:05",
    who: "Ahmed",
    area: "Delivery",
    action: "Changed delivery fee",
    item: "Alexandria",
    link: section("delivery"),
    before: "90 EGP",
    after: "120 EGP",
    from: NASR,
  },
  {
    day: "Yesterday",
    time: "15:52",
    who: "Zain",
    area: "Products",
    action: "Published product",
    item: "Chloé Eau de Parfum 75ml",
    link: product("P1020"),
    before: "Draft",
    after: "Live on site",
    from: MAC,
  },
  {
    day: "Yesterday",
    time: "15:40",
    who: "Zain",
    area: "Products",
    action: "Added product",
    item: "Chloé Eau de Parfum 75ml",
    link: product("P1020"),
    after: "Draft",
    from: MAC,
  },
  {
    day: "Yesterday",
    time: "12:20",
    who: "Ramy Bakr",
    area: "Settings",
    action: "Changed maximum Cash on Delivery order",
    item: "Checkout settings",
    link: section("settings"),
    before: "10,000 EGP",
    after: "15,000 EGP",
    from: EDGE,
  },
  {
    day: "Yesterday",
    time: "11:00",
    who: "Ahmed",
    area: "Orders",
    action: "Cancelled order · customer request",
    item: "ZL-10483",
    link: order("ZL-10483"),
    before: "Pending",
    after: "Cancelled",
    from: NASR,
  },
  {
    day: "Yesterday",
    time: "09:30",
    who: "Ramy Bakr",
    area: "Gift services",
    action: "Turned on feature",
    item: "Gift message card",
    link: section("gifting"),
    before: "Off",
    after: "On",
    from: EDGE,
  },
  {
    day: "22 Sep",
    time: "19:15",
    who: "Zain",
    area: "Content",
    action: "Replaced homepage banner",
    item: "Hero banner",
    link: section("content"),
    before: "Summer edit",
    after: "Autumn gifting",
    from: MAC,
  },
  {
    day: "22 Sep",
    time: "10:40",
    who: "Ahmed",
    area: "Stock",
    action: "Stock count · 1 damaged",
    item: "Guess Luxe Tote Bag",
    link: product("P1014"),
    before: "6",
    after: "5",
    from: NASR,
  },
];

/** Log references count down from the newest entry, like the prototype (LOG-88420 …). */
const NEWEST_REF = 88420;

export const ACTIVITY_LOG: ActivityRow[] = ENTRIES.map((e, i) => ({
  item: "",
  before: "",
  after: "",
  ...e,
  id: `LOG-${NEWEST_REF - i}`,
}));

/** Days offered in the day filter, in the order they appear. */
export const ACTIVITY_DAYS = ["Today", "Yesterday", "22 Sep"];
