/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as BrowsingRouteImport } from './routes/browsing'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as SellingRouteImport } from './routes/selling'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ProductsNewRouteImport } from './routes/products_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsingRoute = BrowsingRouteImport.update({
  id: '/browsing',
  path: '/browsing',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const SellingRoute = SellingRouteImport.update({
  id: '/selling',
  path: '/selling',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/activity': typeof ActivityRoute
  '/approvals': typeof ApprovalsRoute
  '/brands': typeof BrandsRoute
  '/browsing': typeof BrowsingRoute
  '/bundles': typeof BundlesRoute
  '/categories': typeof CategoriesRoute
  '/content': typeof ContentRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRoute
  '/discounts': typeof DiscountsRoute
  '/enquiries': typeof EnquiriesRoute
  '/gifting': typeof GiftingRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/scripts': typeof ScriptsRoute
  '/selling': typeof SellingRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/products/new': typeof ProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/activity': typeof ActivityRoute
  '/approvals': typeof ApprovalsRoute
  '/brands': typeof BrandsRoute
  '/browsing': typeof BrowsingRoute
  '/bundles': typeof BundlesRoute
  '/categories': typeof CategoriesRoute
  '/content': typeof ContentRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRoute
  '/discounts': typeof DiscountsRoute
  '/enquiries': typeof EnquiriesRoute
  '/gifting': typeof GiftingRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/scripts': typeof ScriptsRoute
  '/selling': typeof SellingRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/products/new': typeof ProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/activity': typeof ActivityRoute
  '/approvals': typeof ApprovalsRoute
  '/brands': typeof BrandsRoute
  '/browsing': typeof BrowsingRoute
  '/bundles': typeof BundlesRoute
  '/categories': typeof CategoriesRoute
  '/content': typeof ContentRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRoute
  '/discounts': typeof DiscountsRoute
  '/enquiries': typeof EnquiriesRoute
  '/gifting': typeof GiftingRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/scripts': typeof ScriptsRoute
  '/selling': typeof SellingRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/products_/new': typeof ProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/activity'
    | '/approvals'
    | '/brands'
    | '/browsing'
    | '/bundles'
    | '/categories'
    | '/content'
    | '/customers'
    | '/delivery'
    | '/discounts'
    | '/enquiries'
    | '/gifting'
    | '/inventory'
    | '/login'
    | '/loyalty'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reports'
    | '/returns'
    | '/scripts'
    | '/selling'
    | '/settings'
    | '/staff'
    | '/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/activity'
    | '/approvals'
    | '/brands'
    | '/browsing'
    | '/bundles'
    | '/categories'
    | '/content'
    | '/customers'
    | '/delivery'
    | '/discounts'
    | '/enquiries'
    | '/gifting'
    | '/inventory'
    | '/login'
    | '/loyalty'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reports'
    | '/returns'
    | '/scripts'
    | '/selling'
    | '/settings'
    | '/staff'
    | '/products/new'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/activity'
    | '/approvals'
    | '/brands'
    | '/browsing'
    | '/bundles'
    | '/categories'
    | '/content'
    | '/customers'
    | '/delivery'
    | '/discounts'
    | '/enquiries'
    | '/gifting'
    | '/inventory'
    | '/login'
    | '/loyalty'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reports'
    | '/returns'
    | '/scripts'
    | '/selling'
    | '/settings'
    | '/staff'
    | '/products_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  ActivityRoute: typeof ActivityRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BrandsRoute: typeof BrandsRoute
  BrowsingRoute: typeof BrowsingRoute
  BundlesRoute: typeof BundlesRoute
  CategoriesRoute: typeof CategoriesRoute
  ContentRoute: typeof ContentRoute
  CustomersRoute: typeof CustomersRoute
  DeliveryRoute: typeof DeliveryRoute
  DiscountsRoute: typeof DiscountsRoute
  EnquiriesRoute: typeof EnquiriesRoute
  GiftingRoute: typeof GiftingRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  ReturnsRoute: typeof ReturnsRoute
  ScriptsRoute: typeof ScriptsRoute
  SellingRoute: typeof SellingRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  ProductsNewRoute: typeof ProductsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browsing': {
      id: '/browsing'
      path: '/browsing'
      fullPath: '/browsing'
      preLoaderRoute: typeof BrowsingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selling': {
      id: '/selling'
      path: '/selling'
      fullPath: '/selling'
      preLoaderRoute: typeof SellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/new': {
      id: '/products_/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  ActivityRoute: ActivityRoute,
  ApprovalsRoute: ApprovalsRoute,
  BrandsRoute: BrandsRoute,
  BrowsingRoute: BrowsingRoute,
  BundlesRoute: BundlesRoute,
  CategoriesRoute: CategoriesRoute,
  ContentRoute: ContentRoute,
  CustomersRoute: CustomersRoute,
  DeliveryRoute: DeliveryRoute,
  DiscountsRoute: DiscountsRoute,
  EnquiriesRoute: EnquiriesRoute,
  GiftingRoute: GiftingRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  ReturnsRoute: ReturnsRoute,
  ScriptsRoute: ScriptsRoute,
  SellingRoute: SellingRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  ProductsNewRoute: ProductsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
