/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AttributesRouteImport } from './routes/attributes'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as BrowsingRouteImport } from './routes/browsing'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as SellingRouteImport } from './routes/selling'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AttributesAttributeIdRouteImport } from './routes/attributes_.$attributeId'
import { Route as AttributesNewRouteImport } from './routes/attributes_.new'
import { Route as BrandsBrandIdRouteImport } from './routes/brands_.$brandId'
import { Route as BrandsNewRouteImport } from './routes/brands_.new'
import { Route as BrowsingBrowserIdRouteImport } from './routes/browsing_.$browserId'
import { Route as BundlesBundleIdRouteImport } from './routes/bundles_.$bundleId'
import { Route as BundlesNewRouteImport } from './routes/bundles_.new'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories_.$categoryId'
import { Route as CategoriesNewRouteImport } from './routes/categories_.new'
import { Route as ContentHomepageRouteImport } from './routes/content_.homepage'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers_.$customerId'
import { Route as DiscountsCodeRouteImport } from './routes/discounts_.$code'
import { Route as DiscountsNewRouteImport } from './routes/discounts_.new'
import { Route as EnquiriesEnquiryIdRouteImport } from './routes/enquiries_.$enquiryId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders_.$orderId'
import { Route as OrdersNewRouteImport } from './routes/orders_.new'
import { Route as ProductsProductIdRouteImport } from './routes/products_.$productId'
import { Route as ProductsNewRouteImport } from './routes/products_.new'
import { Route as ReturnsReturnIdRouteImport } from './routes/returns_.$returnId'
import { Route as ScriptsScriptIdRouteImport } from './routes/scripts_.$scriptId'
import { Route as ScriptsNewRouteImport } from './routes/scripts_.new'
import { Route as AttributesAttributeIdValuesRouteImport } from './routes/attributes_.$attributeId_.values'
import { Route as InventoryPreordersProductIdRouteImport } from './routes/inventory_.preorders.$productId'
import { Route as InventoryWaitingProductIdRouteImport } from './routes/inventory_.waiting.$productId'
import { Route as StaffMemberMemberIdRouteImport } from './routes/staff_.member.$memberId'
import { Route as StaffRoleRoleIdRouteImport } from './routes/staff_.role.$roleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributesRoute = AttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsingRoute = BrowsingRouteImport.update({
  id: '/browsing',
  path: '/browsing',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const SellingRoute = SellingRouteImport.update({
  id: '/selling',
  path: '/selling',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributesAttributeIdRoute = AttributesAttributeIdRouteImport.update({
  id: '/attributes_/$attributeId',
  path: '/attributes/$attributeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributesNewRoute = AttributesNewRouteImport.update({
  id: '/attributes_/new',
  path: '/attributes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands_/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsNewRoute = BrandsNewRouteImport.update({
  id: '/brands_/new',
  path: '/brands/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsingBrowserIdRoute = BrowsingBrowserIdRouteImport.update({
  id: '/browsing_/$browserId',
  path: '/browsing/$browserId',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesBundleIdRoute = BundlesBundleIdRouteImport.update({
  id: '/bundles_/$bundleId',
  path: '/bundles/$bundleId',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesNewRoute = BundlesNewRouteImport.update({
  id: '/bundles_/new',
  path: '/bundles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories_/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewRoute = CategoriesNewRouteImport.update({
  id: '/categories_/new',
  path: '/categories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentHomepageRoute = ContentHomepageRouteImport.update({
  id: '/content_/homepage',
  path: '/content/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers_/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsCodeRoute = DiscountsCodeRouteImport.update({
  id: '/discounts_/$code',
  path: '/discounts/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsNewRoute = DiscountsNewRouteImport.update({
  id: '/discounts_/new',
  path: '/discounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesEnquiryIdRoute = EnquiriesEnquiryIdRouteImport.update({
  id: '/enquiries_/$enquiryId',
  path: '/enquiries/$enquiryId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders_/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders_/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products_/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsReturnIdRoute = ReturnsReturnIdRouteImport.update({
  id: '/returns_/$returnId',
  path: '/returns/$returnId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsScriptIdRoute = ScriptsScriptIdRouteImport.update({
  id: '/scripts_/$scriptId',
  path: '/scripts/$scriptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsNewRoute = ScriptsNewRouteImport.update({
  id: '/scripts_/new',
  path: '/scripts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributesAttributeIdValuesRoute =
  AttributesAttributeIdValuesRouteImport.update({
    id: '/attributes_/$attributeId_/values',
    path: '/attributes/$attributeId/values',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventoryPreordersProductIdRoute =
  InventoryPreordersProductIdRouteImport.update({
    id: '/inventory_/preorders/$productId',
    path: '/inventory/preorders/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventoryWaitingProductIdRoute =
  InventoryWaitingProductIdRouteImport.update({
    id: '/inventory_/waiting/$productId',
    path: '/inventory/waiting/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffMemberMemberIdRoute = StaffMemberMemberIdRouteImport.update({
  id: '/staff_/member/$memberId',
  path: '/staff/member/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoleRoleIdRoute = StaffRoleRoleIdRouteImport.update({
  id: '/staff_/role/$roleId',
  path: '/staff/role/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/activity': typeof ActivityRoute
  '/approvals': typeof ApprovalsRoute
  '/attributes': typeof AttributesRoute
  '/brands': typeof BrandsRoute
  '/browsing': typeof BrowsingRoute
  '/bundles': typeof BundlesRoute
  '/categories': typeof CategoriesRoute
  '/content': typeof ContentRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRoute
  '/discounts': typeof DiscountsRoute
  '/enquiries': typeof EnquiriesRoute
  '/gifting': typeof GiftingRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/scripts': typeof ScriptsRoute
  '/selling': typeof SellingRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/attributes/$attributeId': typeof AttributesAttributeIdRoute
  '/attributes/new': typeof AttributesNewRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/new': typeof BrandsNewRoute
  '/browsing/$browserId': typeof BrowsingBrowserIdRoute
  '/bundles/$bundleId': typeof BundlesBundleIdRoute
  '/bundles/new': typeof BundlesNewRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/new': typeof CategoriesNewRoute
  '/content/homepage': typeof ContentHomepageRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/discounts/$code': typeof DiscountsCodeRoute
  '/discounts/new': typeof DiscountsNewRoute
  '/enquiries/$enquiryId': typeof EnquiriesEnquiryIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/returns/$returnId': typeof ReturnsReturnIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
  '/scripts/new': typeof ScriptsNewRoute
  '/attributes/$attributeId/values': typeof AttributesAttributeIdValuesRoute
  '/inventory/preorders/$productId': typeof InventoryPreordersProductIdRoute
  '/inventory/waiting/$productId': typeof InventoryWaitingProductIdRoute
  '/staff/member/$memberId': typeof StaffMemberMemberIdRoute
  '/staff/role/$roleId': typeof StaffRoleRoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/activity': typeof ActivityRoute
  '/approvals': typeof ApprovalsRoute
  '/attributes': typeof AttributesRoute
  '/brands': typeof BrandsRoute
  '/browsing': typeof BrowsingRoute
  '/bundles': typeof BundlesRoute
  '/categories': typeof CategoriesRoute
  '/content': typeof ContentRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRoute
  '/discounts': typeof DiscountsRoute
  '/enquiries': typeof EnquiriesRoute
  '/gifting': typeof GiftingRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/scripts': typeof ScriptsRoute
  '/selling': typeof SellingRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/attributes/$attributeId': typeof AttributesAttributeIdRoute
  '/attributes/new': typeof AttributesNewRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/new': typeof BrandsNewRoute
  '/browsing/$browserId': typeof BrowsingBrowserIdRoute
  '/bundles/$bundleId': typeof BundlesBundleIdRoute
  '/bundles/new': typeof BundlesNewRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/new': typeof CategoriesNewRoute
  '/content/homepage': typeof ContentHomepageRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/discounts/$code': typeof DiscountsCodeRoute
  '/discounts/new': typeof DiscountsNewRoute
  '/enquiries/$enquiryId': typeof EnquiriesEnquiryIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/returns/$returnId': typeof ReturnsReturnIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
  '/scripts/new': typeof ScriptsNewRoute
  '/attributes/$attributeId/values': typeof AttributesAttributeIdValuesRoute
  '/inventory/preorders/$productId': typeof InventoryPreordersProductIdRoute
  '/inventory/waiting/$productId': typeof InventoryWaitingProductIdRoute
  '/staff/member/$memberId': typeof StaffMemberMemberIdRoute
  '/staff/role/$roleId': typeof StaffRoleRoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/activity': typeof ActivityRoute
  '/approvals': typeof ApprovalsRoute
  '/attributes': typeof AttributesRoute
  '/brands': typeof BrandsRoute
  '/browsing': typeof BrowsingRoute
  '/bundles': typeof BundlesRoute
  '/categories': typeof CategoriesRoute
  '/content': typeof ContentRoute
  '/customers': typeof CustomersRoute
  '/delivery': typeof DeliveryRoute
  '/discounts': typeof DiscountsRoute
  '/enquiries': typeof EnquiriesRoute
  '/gifting': typeof GiftingRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/scripts': typeof ScriptsRoute
  '/selling': typeof SellingRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/attributes_/$attributeId': typeof AttributesAttributeIdRoute
  '/attributes_/new': typeof AttributesNewRoute
  '/brands_/$brandId': typeof BrandsBrandIdRoute
  '/brands_/new': typeof BrandsNewRoute
  '/browsing_/$browserId': typeof BrowsingBrowserIdRoute
  '/bundles_/$bundleId': typeof BundlesBundleIdRoute
  '/bundles_/new': typeof BundlesNewRoute
  '/categories_/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories_/new': typeof CategoriesNewRoute
  '/content_/homepage': typeof ContentHomepageRoute
  '/customers_/$customerId': typeof CustomersCustomerIdRoute
  '/discounts_/$code': typeof DiscountsCodeRoute
  '/discounts_/new': typeof DiscountsNewRoute
  '/enquiries_/$enquiryId': typeof EnquiriesEnquiryIdRoute
  '/orders_/$orderId': typeof OrdersOrderIdRoute
  '/orders_/new': typeof OrdersNewRoute
  '/products_/$productId': typeof ProductsProductIdRoute
  '/products_/new': typeof ProductsNewRoute
  '/returns_/$returnId': typeof ReturnsReturnIdRoute
  '/scripts_/$scriptId': typeof ScriptsScriptIdRoute
  '/scripts_/new': typeof ScriptsNewRoute
  '/attributes_/$attributeId_/values': typeof AttributesAttributeIdValuesRoute
  '/inventory_/preorders/$productId': typeof InventoryPreordersProductIdRoute
  '/inventory_/waiting/$productId': typeof InventoryWaitingProductIdRoute
  '/staff_/member/$memberId': typeof StaffMemberMemberIdRoute
  '/staff_/role/$roleId': typeof StaffRoleRoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/activity'
    | '/approvals'
    | '/attributes'
    | '/brands'
    | '/browsing'
    | '/bundles'
    | '/categories'
    | '/content'
    | '/customers'
    | '/delivery'
    | '/discounts'
    | '/enquiries'
    | '/gifting'
    | '/inventory'
    | '/login'
    | '/loyalty'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reports'
    | '/returns'
    | '/scripts'
    | '/selling'
    | '/settings'
    | '/staff'
    | '/attributes/$attributeId'
    | '/attributes/new'
    | '/brands/$brandId'
    | '/brands/new'
    | '/browsing/$browserId'
    | '/bundles/$bundleId'
    | '/bundles/new'
    | '/categories/$categoryId'
    | '/categories/new'
    | '/content/homepage'
    | '/customers/$customerId'
    | '/discounts/$code'
    | '/discounts/new'
    | '/enquiries/$enquiryId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/products/$productId'
    | '/products/new'
    | '/returns/$returnId'
    | '/scripts/$scriptId'
    | '/scripts/new'
    | '/attributes/$attributeId/values'
    | '/inventory/preorders/$productId'
    | '/inventory/waiting/$productId'
    | '/staff/member/$memberId'
    | '/staff/role/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/activity'
    | '/approvals'
    | '/attributes'
    | '/brands'
    | '/browsing'
    | '/bundles'
    | '/categories'
    | '/content'
    | '/customers'
    | '/delivery'
    | '/discounts'
    | '/enquiries'
    | '/gifting'
    | '/inventory'
    | '/login'
    | '/loyalty'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reports'
    | '/returns'
    | '/scripts'
    | '/selling'
    | '/settings'
    | '/staff'
    | '/attributes/$attributeId'
    | '/attributes/new'
    | '/brands/$brandId'
    | '/brands/new'
    | '/browsing/$browserId'
    | '/bundles/$bundleId'
    | '/bundles/new'
    | '/categories/$categoryId'
    | '/categories/new'
    | '/content/homepage'
    | '/customers/$customerId'
    | '/discounts/$code'
    | '/discounts/new'
    | '/enquiries/$enquiryId'
    | '/orders/$orderId'
    | '/orders/new'
    | '/products/$productId'
    | '/products/new'
    | '/returns/$returnId'
    | '/scripts/$scriptId'
    | '/scripts/new'
    | '/attributes/$attributeId/values'
    | '/inventory/preorders/$productId'
    | '/inventory/waiting/$productId'
    | '/staff/member/$memberId'
    | '/staff/role/$roleId'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/activity'
    | '/approvals'
    | '/attributes'
    | '/brands'
    | '/browsing'
    | '/bundles'
    | '/categories'
    | '/content'
    | '/customers'
    | '/delivery'
    | '/discounts'
    | '/enquiries'
    | '/gifting'
    | '/inventory'
    | '/login'
    | '/loyalty'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reports'
    | '/returns'
    | '/scripts'
    | '/selling'
    | '/settings'
    | '/staff'
    | '/attributes_/$attributeId'
    | '/attributes_/new'
    | '/brands_/$brandId'
    | '/brands_/new'
    | '/browsing_/$browserId'
    | '/bundles_/$bundleId'
    | '/bundles_/new'
    | '/categories_/$categoryId'
    | '/categories_/new'
    | '/content_/homepage'
    | '/customers_/$customerId'
    | '/discounts_/$code'
    | '/discounts_/new'
    | '/enquiries_/$enquiryId'
    | '/orders_/$orderId'
    | '/orders_/new'
    | '/products_/$productId'
    | '/products_/new'
    | '/returns_/$returnId'
    | '/scripts_/$scriptId'
    | '/scripts_/new'
    | '/attributes_/$attributeId_/values'
    | '/inventory_/preorders/$productId'
    | '/inventory_/waiting/$productId'
    | '/staff_/member/$memberId'
    | '/staff_/role/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  ActivityRoute: typeof ActivityRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AttributesRoute: typeof AttributesRoute
  BrandsRoute: typeof BrandsRoute
  BrowsingRoute: typeof BrowsingRoute
  BundlesRoute: typeof BundlesRoute
  CategoriesRoute: typeof CategoriesRoute
  ContentRoute: typeof ContentRoute
  CustomersRoute: typeof CustomersRoute
  DeliveryRoute: typeof DeliveryRoute
  DiscountsRoute: typeof DiscountsRoute
  EnquiriesRoute: typeof EnquiriesRoute
  GiftingRoute: typeof GiftingRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  ReturnsRoute: typeof ReturnsRoute
  ScriptsRoute: typeof ScriptsRoute
  SellingRoute: typeof SellingRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  AttributesAttributeIdRoute: typeof AttributesAttributeIdRoute
  AttributesNewRoute: typeof AttributesNewRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  BrandsNewRoute: typeof BrandsNewRoute
  BrowsingBrowserIdRoute: typeof BrowsingBrowserIdRoute
  BundlesBundleIdRoute: typeof BundlesBundleIdRoute
  BundlesNewRoute: typeof BundlesNewRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  CategoriesNewRoute: typeof CategoriesNewRoute
  ContentHomepageRoute: typeof ContentHomepageRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  DiscountsCodeRoute: typeof DiscountsCodeRoute
  DiscountsNewRoute: typeof DiscountsNewRoute
  EnquiriesEnquiryIdRoute: typeof EnquiriesEnquiryIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ReturnsReturnIdRoute: typeof ReturnsReturnIdRoute
  ScriptsScriptIdRoute: typeof ScriptsScriptIdRoute
  ScriptsNewRoute: typeof ScriptsNewRoute
  AttributesAttributeIdValuesRoute: typeof AttributesAttributeIdValuesRoute
  InventoryPreordersProductIdRoute: typeof InventoryPreordersProductIdRoute
  InventoryWaitingProductIdRoute: typeof InventoryWaitingProductIdRoute
  StaffMemberMemberIdRoute: typeof StaffMemberMemberIdRoute
  StaffRoleRoleIdRoute: typeof StaffRoleRoleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributes': {
      id: '/attributes'
      path: '/attributes'
      fullPath: '/attributes'
      preLoaderRoute: typeof AttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browsing': {
      id: '/browsing'
      path: '/browsing'
      fullPath: '/browsing'
      preLoaderRoute: typeof BrowsingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selling': {
      id: '/selling'
      path: '/selling'
      fullPath: '/selling'
      preLoaderRoute: typeof SellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributes_/$attributeId': {
      id: '/attributes_/$attributeId'
      path: '/attributes/$attributeId'
      fullPath: '/attributes/$attributeId'
      preLoaderRoute: typeof AttributesAttributeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributes_/new': {
      id: '/attributes_/new'
      path: '/attributes/new'
      fullPath: '/attributes/new'
      preLoaderRoute: typeof AttributesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands_/$brandId': {
      id: '/brands_/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands_/new': {
      id: '/brands_/new'
      path: '/brands/new'
      fullPath: '/brands/new'
      preLoaderRoute: typeof BrandsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browsing_/$browserId': {
      id: '/browsing_/$browserId'
      path: '/browsing/$browserId'
      fullPath: '/browsing/$browserId'
      preLoaderRoute: typeof BrowsingBrowserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles_/$bundleId': {
      id: '/bundles_/$bundleId'
      path: '/bundles/$bundleId'
      fullPath: '/bundles/$bundleId'
      preLoaderRoute: typeof BundlesBundleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles_/new': {
      id: '/bundles_/new'
      path: '/bundles/new'
      fullPath: '/bundles/new'
      preLoaderRoute: typeof BundlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories_/$categoryId': {
      id: '/categories_/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories_/new': {
      id: '/categories_/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof CategoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content_/homepage': {
      id: '/content_/homepage'
      path: '/content/homepage'
      fullPath: '/content/homepage'
      preLoaderRoute: typeof ContentHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/$customerId': {
      id: '/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts_/$code': {
      id: '/discounts_/$code'
      path: '/discounts/$code'
      fullPath: '/discounts/$code'
      preLoaderRoute: typeof DiscountsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts_/new': {
      id: '/discounts_/new'
      path: '/discounts/new'
      fullPath: '/discounts/new'
      preLoaderRoute: typeof DiscountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries_/$enquiryId': {
      id: '/enquiries_/$enquiryId'
      path: '/enquiries/$enquiryId'
      fullPath: '/enquiries/$enquiryId'
      preLoaderRoute: typeof EnquiriesEnquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/$orderId': {
      id: '/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/new': {
      id: '/orders_/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$productId': {
      id: '/products_/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/new': {
      id: '/products_/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns_/$returnId': {
      id: '/returns_/$returnId'
      path: '/returns/$returnId'
      fullPath: '/returns/$returnId'
      preLoaderRoute: typeof ReturnsReturnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts_/$scriptId': {
      id: '/scripts_/$scriptId'
      path: '/scripts/$scriptId'
      fullPath: '/scripts/$scriptId'
      preLoaderRoute: typeof ScriptsScriptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts_/new': {
      id: '/scripts_/new'
      path: '/scripts/new'
      fullPath: '/scripts/new'
      preLoaderRoute: typeof ScriptsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributes_/$attributeId_/values': {
      id: '/attributes_/$attributeId_/values'
      path: '/attributes/$attributeId/values'
      fullPath: '/attributes/$attributeId/values'
      preLoaderRoute: typeof AttributesAttributeIdValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/preorders/$productId': {
      id: '/inventory_/preorders/$productId'
      path: '/inventory/preorders/$productId'
      fullPath: '/inventory/preorders/$productId'
      preLoaderRoute: typeof InventoryPreordersProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/waiting/$productId': {
      id: '/inventory_/waiting/$productId'
      path: '/inventory/waiting/$productId'
      fullPath: '/inventory/waiting/$productId'
      preLoaderRoute: typeof InventoryWaitingProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff_/member/$memberId': {
      id: '/staff_/member/$memberId'
      path: '/staff/member/$memberId'
      fullPath: '/staff/member/$memberId'
      preLoaderRoute: typeof StaffMemberMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff_/role/$roleId': {
      id: '/staff_/role/$roleId'
      path: '/staff/role/$roleId'
      fullPath: '/staff/role/$roleId'
      preLoaderRoute: typeof StaffRoleRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  ActivityRoute: ActivityRoute,
  ApprovalsRoute: ApprovalsRoute,
  AttributesRoute: AttributesRoute,
  BrandsRoute: BrandsRoute,
  BrowsingRoute: BrowsingRoute,
  BundlesRoute: BundlesRoute,
  CategoriesRoute: CategoriesRoute,
  ContentRoute: ContentRoute,
  CustomersRoute: CustomersRoute,
  DeliveryRoute: DeliveryRoute,
  DiscountsRoute: DiscountsRoute,
  EnquiriesRoute: EnquiriesRoute,
  GiftingRoute: GiftingRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  ReturnsRoute: ReturnsRoute,
  ScriptsRoute: ScriptsRoute,
  SellingRoute: SellingRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  AttributesAttributeIdRoute: AttributesAttributeIdRoute,
  AttributesNewRoute: AttributesNewRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  BrandsNewRoute: BrandsNewRoute,
  BrowsingBrowserIdRoute: BrowsingBrowserIdRoute,
  BundlesBundleIdRoute: BundlesBundleIdRoute,
  BundlesNewRoute: BundlesNewRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  CategoriesNewRoute: CategoriesNewRoute,
  ContentHomepageRoute: ContentHomepageRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  DiscountsCodeRoute: DiscountsCodeRoute,
  DiscountsNewRoute: DiscountsNewRoute,
  EnquiriesEnquiryIdRoute: EnquiriesEnquiryIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  ReturnsReturnIdRoute: ReturnsReturnIdRoute,
  ScriptsScriptIdRoute: ScriptsScriptIdRoute,
  ScriptsNewRoute: ScriptsNewRoute,
  AttributesAttributeIdValuesRoute: AttributesAttributeIdValuesRoute,
  InventoryPreordersProductIdRoute: InventoryPreordersProductIdRoute,
  InventoryWaitingProductIdRoute: InventoryWaitingProductIdRoute,
  StaffMemberMemberIdRoute: StaffMemberMemberIdRoute,
  StaffRoleRoleIdRoute: StaffRoleRoleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
